worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Логирование: stdout для access, stderr для error
    access_log /dev/stdout;
    error_log /dev/stderr info;

    proxy_cache_path /var/cache/nginx
        levels=1:2
        keys_zone=report_cache:100m
        max_size=1g
        inactive=60m
        use_temp_path=off;

    server {

        listen 80;

        location /api/reports {

            proxy_pass http://report-service:8086;

            proxy_cache report_cache;
            proxy_cache_methods GET;
            #proxy_cache_key "$scheme$request_method$host$request_uri";
            proxy_cache_key "$arg_clientId";
            proxy_cache_valid 200 10m;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}