version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data2:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8082

  bionicpro-auth:
    build:
      context: ./bionicpro-auth/
      dockerfile: Dockerfile
    container_name: bionicpro-auth
    ports:
      - "8082:8082"
    depends_on:
      - redis
    volumes:
      - ./bionicpro-auth-keys:/keys
    environment:
      SESSION_TTL: "00:02:00"
      COOKIE_MAX_AGE: "00:05:00"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]  # включаем AOF-персистентность
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

volumes:
  redis_data:
  #bionicpro-auth-keys:

networks:
  app-network:
    name: app-network
    driver: bridge